# Generated by Django 5.2.8 on 2025-11-24 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelstation',
            name='opis_id',
            field=models.CharField(max_length=50),
        ),
    ]
