"""
Django settings for main project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

from django_settings.settings import DjangoSettings, DatabaseConfig, DjangoDatabases

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Database

class DatabasesSettings(DjangoDatabases):
    default = DatabaseConfig(**{
        'ENGINE': 'django.contrib.gis.db.backends.postgis',
        'NAME': 'route_planner',
        'USER': 'postgres',
        'PASSWORD': 'postgres',
        'HOST': 'localhost',
        'PORT': '5432',
    })
    sqllite = DatabaseConfig(**{
        'engine': 'django.db.backends.sqlite3',
        'name': BASE_DIR / 'db.sqlite3',
    })

djsettings = DjangoSettings(
    template_dirs = [BASE_DIR / 'templates'],
    databases=DatabasesSettings()
)

djsettings.allowed_hosts = []


# Application definition

djsettings.installed_apps += [
    'django.contrib.gis',
    'rest_framework',
    'routing'
]

djsettings.root_urlconf = 'main.urls'

djsettings.wsgi_application = 'main.wsgi.application'


djsettings.static_root = BASE_DIR / "static"

# Create logs directory if it doesn't exist
(BASE_DIR / 'logs').mkdir(exist_ok=True)


djsettings.rest_framework = {
    'TEST_REQUEST_RENDERER_CLASSES': [
        'rest_framework.renderers.MultiPartRenderer',
        'rest_framework.renderers.JSONRenderer',
    ]
}
